[Unit]
Description=Tailscale Agent
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/bin/tailscaled --state=/var/lib/tailscale/tailscaled.state
ExecStopPost=/usr/bin/tailscale down
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
